# Generated by Django 2.2.13 on 2023-05-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_camera_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_camera_location',
            old_name='Video',
            new_name='CAM_ID',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='Video',
            new_name='CAM_ID',
        ),
    ]
