# Generated by Django 2.2.13 on 2023-05-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20230508_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='Longitude',
        ),
    ]
